apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic.fullname" . }}-es-roles
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.elasticConfigJob.roles }}
  {{ $key }}.json: |
{{- toJson $value | nindent 4 }}
{{- end }}
