apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic.fullname" . }}-es-roles
  namespace: {{ .Release.Namespace }}
data:
  roles.yml: |
{{- toYaml .Values.elasticConfigJob.roles | nindent 4 }}
