apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic.fullname" . }}-es-script
  namespace: {{ .Release.Namespace }}
data:
  setup.sh: |
    #!/bin/bash

    while [[ "$(curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done

    cat /workdir/roles.json | jq -c 'to_entries[]' \
        | while read object; \
        do curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} ${ES_URL}/_security/role/$(jq -r '.key' <<< $object) -H "Content-Type: application/json" -d "$(jq -r ".value" <<< $object)"; \
        done;
    # Create user with outofschool role
    curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} ${ES_URL}/_security/user/webapi -H "Content-Type: application/json" -d "{\"password\": \"${API_PASS}\", \"roles\" : [ \"outofschool\" ]}"
