apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic.fullname" . }}-es-script
  namespace: {{ .Release.Namespace }}
data:
  setup.sh: |
    #!/bin/bash

    echo "Starting job..."
    while [[ "$(curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done

    ROLES=(/etc/roles/*.json)
    for role in "${ROLES[@]}"
    do
      NAME=$(basename $role)
      echo "Updating role: ${NAME}..."
      curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} ${ES_URL}/_security/role/${NAME%.json} -H "Content-Type: application/json" -d @$role
      echo "Done..."
    done

    # Create user with outofschool role
    # TODO: add multiple roles from list if needed
    echo "Creating user with role..."
    curl -s -o /dev/null -u elastic:${ADMIN_PASSWORD} ${ES_URL}/_security/user/webapi -H "Content-Type: application/json" -d "{\"password\": \"${API_PASS}\", \"roles\" : [ \"outofschool\" ]}"
    echo "Done..."
