steps:
# Build the container image
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - build
    - gcr.io/$PROJECT_ID/oos-api:$SHORT_SHA
    - --cache-image=gcr.io/$PROJECT_ID/oos-api:cache
    - --builder=paketobuildpacks/builder:full
    - --buildpack=fagiani/apt
    # TODO: after paketo-buildpacks/dotnet-core buildpack fix revert to using latest version
    # - --buildpack=gcr.io/paketo-buildpacks/dotnet-core
    - --buildpack=docker:///gcr.io/paketo-buildpacks/dotnet-core:0.16.1
    - --env=BP_DOTNET_PROJECT_PATH=./OutOfSchool/OutOfSchool.WebApi/
    - --publish
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - beta
    - run
    - deploy
    - apiservice
    - --image
    - gcr.io/$PROJECT_ID/oos-api:$SHORT_SHA
    - --region
    - $_REGION
    - --platform
    - managed
    - --allow-unauthenticated
    - --service-account
    - $_SERVICE_ACCOUNT
    - --cpu=2
    - --memory=512Mi
    - --max-instances=3
    - --concurrency=80
    - --set-env-vars=ASPNETCORE_ENVIRONMENT=Google
    - --set-env-vars=Elasticsearch__User=webapi
    - --set-env-vars=ConnectionStrings__ExternalImageStorage__DatabaseName=outofschool
    - --set-env-vars=GoogleCloudPlatform__Storage__OosImages__BucketName=$_BUCKET
    # Cloud Run fails to set the variable as an array :(
    # Using index instead
    - --set-env-vars=Elasticsearch__Urls__0=https://elastic.dmytrominochkin.cloud/
    - --set-secrets=ConnectionStrings__DefaultConnection=$_CONN_STRING_SECRET,Elasticsearch__Password=$_ES_PASSWORD
    # Disable http2 because prod will be http1.1 for now
    - --no-use-http2
# Clean old versions except previous Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - for revision in `gcloud run revisions list --service apiservice --platform managed --region $_REGION --format 'value(name)' | sort -r | tail -n +3 | paste -sd " " -`; do $(yes | gcloud run revisions delete --platform managed --region $_REGION $revision) || exit 0; done;
