steps:
# Build the container image
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - build
    - gcr.io/$PROJECT_ID/oos-api:$SHORT_SHA
    - --cache-image=gcr.io/$PROJECT_ID/oos-api:cache
    - --builder=paketobuildpacks/builder:full
    - --buildpack=fagiani/apt
    # TODO: after paketo-buildpacks/dotnet-core buildpack fix revert to using latest version
    # - --buildpack=gcr.io/paketo-buildpacks/dotnet-core
    - --buildpack=docker:///gcr.io/paketo-buildpacks/dotnet-core:0.16.1
    - --env=BP_DOTNET_PROJECT_PATH=./OutOfSchool/OutOfSchool.WebApi/
    - --publish
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - beta
    - run
    - deploy
    - apiservice
    - --image
    - gcr.io/$PROJECT_ID/oos-api:$SHORT_SHA
    - --region
    - $_REGION
    - --platform
    - managed
    - --allow-unauthenticated
    - --service-account
    - $_SERVICE_ACCOUNT
    - --cpu=2
    - --memory=512Mi
    - --max-instances=3
    - --concurrency=200
    - --timeout=120
    - --set-env-vars=ASPNETCORE_ENVIRONMENT=Google
    - --set-env-vars=Elasticsearch__User=webapi
    - --set-env-vars=ConnectionStringsOverride__DefaultConnection__UserId=api
    - --set-env-vars=GoogleCloudPlatform__Storage__OosImages__BucketName=$_BUCKET
    - --set-env-vars=Redis__Server=$_REDIS_HOST
    - --set-secrets=ConnectionStringsOverride__DefaultConnection__Password=$_DB_PASS,Elasticsearch__Password=$_ES_PASSWORD,Redis__Password=$_REDIS_PASS
    - --no-use-http2
# Clean old versions except previous Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - for revision in `gcloud run revisions list --service apiservice --platform managed --region $_REGION --format 'value(name)' | sort -r | tail -n +3 | paste -sd " " -`; do $(yes | gcloud run revisions delete --platform managed --region $_REGION $revision) || exit 0; done;
