steps:
# Build the container image
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - build
    - gcr.io/$PROJECT_ID/oos-auth:$SHORT_SHA
    - --buildpack=gcr.io/paketo-buildpacks/dotnet-core
    - --builder=paketobuildpacks/builder:base
    - --env=BP_DOTNET_PROJECT_PATH=./OutOfSchool/OutOfSchool.IdentityServer/
    - --publish
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - beta
    - run
    - deploy
    - authservice
    - --image
    - gcr.io/$PROJECT_ID/oos-auth:$SHORT_SHA
    - --region
    - $_REGION
    - --platform
    - managed
    - --allow-unauthenticated
    - --service-account
    - $_SERVICE_ACCOUNT
    - --cpu=2
    - --memory=512Mi
    - --max-instances=2
    - --concurrency=80
    - --set-env-vars=ASPNETCORE_ENVIRONMENT=Google
    - --set-env-vars=Email__AddressFrom=$_SENDER_EMAIL
    - --set-env-vars=Email__Smtp__Username=$_SENDER_EMAIL
    - --set-secrets=ConnectionStrings__DefaultConnection=$_CONN_STRING_SECRET,Email__Smtp__Password=$_SENDER_PASSWORD
    # Disable http2 because prod will be http1.1 for now
    - --no-use-http2
# Clean old versions except previous Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - for revision in `gcloud run revisions list --service authservice --platform managed --region $_REGION --format 'value(name)' | sort -r | tail -n +3 | paste -sd " " -`; do $(yes | gcloud run revisions delete --platform managed --region $_REGION $revision) || exit 0; done;