steps:
# Build the container image
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args:
    - build
    - gcr.io/$PROJECT_ID/oos-auth:$SHORT_SHA
    - --cache-image=gcr.io/$PROJECT_ID/oos-auth:cache
    - --buildpack=gcr.io/paketo-buildpacks/dotnet-core
    - --buildpack=gcr.io/paketo-buildpacks/environment-variables
    - --builder=paketobuildpacks/builder:base
    - --env=BP_DOTNET_PROJECT_PATH=./OutOfSchool/OutOfSchool.IdentityServer/
    - --env=BPE_AppDefaults__Version=$SHORT_SHA
    - --publish
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - beta
    - run
    - deploy
    - authservice
    - --image
    - gcr.io/$PROJECT_ID/oos-auth:$SHORT_SHA
    - --region
    - $_REGION
    - --platform
    - managed
    - --ingress
    - internal-and-cloud-load-balancing
    - --allow-unauthenticated
    - --service-account
    - $_SERVICE_ACCOUNT
    - --cpu=2
    - --memory=512Mi
    - --max-instances=3
    - --concurrency=120
    - --set-env-vars=ASPNETCORE_ENVIRONMENT=$_ASPNETCORE_ENVIRONMENT
    - --set-env-vars=Email__AddressFrom=$_SENDER_EMAIL
    - --set-env-vars=ConnectionStringsOverride__DefaultConnection__UserId=oos
    - --set-env-vars=ConnectionStringsOverride__DefaultConnection__Port=$_SQL_PORT
    - --set-env-vars=AppDefaults__Version=$SHORT_SHA
    - --set-secrets=ConnectionStringsOverride__DefaultConnection__Password=$_DB_PASS,Email__SendGridKey=$_SENDGRID_KEY
    # Disable http2 because prod will be http1.1 for now
    - --no-use-http2
# Clean old versions except previous Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args:
    - -c
    - for revision in `gcloud run revisions list --service authservice --platform managed --region $_REGION --format 'value(name)' | sort -r | tail -n +3 | paste -sd " " -`; do $(yes | gcloud run revisions delete --platform managed --region $_REGION $revision) || exit 0; done;
