# Trigger extracts the commit timestamp as _COMMIT_DATE_RAW from $(commit.commit.committer.date) event payload
# and uses bash variable expansion to convert it to _COMMIT_DATE as ${_COMMIT_DATE_RAW//:/-}
steps:
# Build .Net Migrations Bundle as container image
- name: gcr.io/kaniko-project/executor:latest
  args:
  - --dockerfile=OutOfSchool/OutOfSchool.Migrations/Dockerfile
  - --context=dir://OutOfSchool
  - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/outofschool/oos-migrations:$SHORT_SHA
  - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/outofschool/oos-migrations:$SHORT_SHA-${_COMMIT_DATE}
  - --cache=true
  - --cache-repo=${_REGION}-docker.pkg.dev/$PROJECT_ID/outofschool/kaniko-cache
  - --reproducible
  # Use experimental flag to minimize build speeds
  - --use-new-run
options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
