version: '3.4'
services:
# === SQL SERVER ===
  sql-server:
    image: mcr.microsoft.com/mssql/server:${SQL_VERSION}
    command: /bin/bash ./usr/config/entrypoint.sh
    environment:
      ACCEPT_EULA: Y
      TZ: Europe/Kiev
      MSSQL_COLLATION: Ukrainian_100_CI_AS
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
      - ./MSSQL/entrypoint.sh:/usr/config/entrypoint.sh:ro
      - ./MSSQL/configure-db.sh:/usr/config/configure-db.sh:ro
      - ./MSSQL/configure-db.sql:/usr/config/configure-db.sql:ro
    networks:
      - db
# === OPENSEARCH ===
  opensearch:
    image: opensearchproject/opensearch:1.0.1
    container_name: opensearch-node1
    # command: >
    #   /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-ukrainian 
    #   || ./bin/elasticsearch-plugin install analysis-icu analysis-ukrainian mapper-murmur3 mapper-size; 
    #   /usr/local/bin/docker-entrypoint.sh"
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - db
# === OPENSEARCH DASHBPARDS ===
  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:1.0.1
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    networks:
      - db
# === IDENTITY SERVER ===
  identity-server:
    image: ${OOS_AUTH_IMAGE}:${TAG}
    environment:
      PORT: "5443"
      ReverseProxy__BasePath: /identity
    depends_on:
      - sql-server
    networks:
      - db
      - web
# === WEB API ===
  webapi-server:
    image: ${OOS_API_IMAGE}:${TAG}
    environment:
      PORT: "5000"
      ReverseProxy__BasePath: /webapi
      Logging__FilePath: /var/log/oos/api.log
    volumes:
      - api-logs:/var/log/oos:rw
    depends_on:
      - identity-server
    networks:
      - db
      - web
# === REVERSE PROXY ===
  nginx:
    image: ${OOS_NGINX_IMAGE}:${TAG}
    container_name: oos.local
    environment:
      PORT: "80"
      SSL_PORT: "443"
    depends_on:
      - identity-server
      - webapi-server
    networks:
      - web
# === FRONTEND ===
  frontend:
    image: nginx:latest
    container_name: frontend
    networks:
      - web
# === VOLUMES ===
volumes:
  sql-data:
    driver: local
  api-logs:
    driver: local
# === NETWORKS ===
networks:
  db:
    driver: bridge
  web:
    driver: bridge