# Local values override
pvc:
  mysql:
    size: 1G
    storageClass: hostpath

mysql:
  enabled: true
  primary:
    persistence:
      enabled: true
      # storageClass: "hostpath"
      # accessModes:
      # - ReadWriteOnce
      # size: 1Gi 
    extraEnvVarsSecret: mysql-api-auth

## If you want - you can enable PHPMyAdmin but don't turn ingress on, as it won't work localy atm
## Use port forwarding: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/
phpmyadmin:
  enabled: false
  ingress:
    enabled: false
  db:
    allowArbitraryServer: false
    host: "outofschool-mysql"