# Default values for infrastructure.
# This is a YAML-formatted file.

ingress-nginx:
  enabled: false
  controller:
    config:
      proxy-body-size: 100m
    service:
      enabled: true
      # type: ClusterIP
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  defaultBackend:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
