// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutOfSchool.Services;

namespace OutOfSchool.IdentityServer.Data.Migrations.FilesMigrations
{
    [DbContext(typeof(FilesDbContext))]
    [Migration("20220222122842_AddedImagesContentTypes")]
    partial class AddedImagesContentTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("OutOfSchool.Services.Models.Images.DbImageContentTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentTypeValue")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ImageContentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentTypeValue = "image/jpeg"
                        },
                        new
                        {
                            Id = 2,
                            ContentTypeValue = "image/png"
                        });
                });

            modelBuilder.Entity("OutOfSchool.Services.Models.Images.DbImageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("File")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("OutOfSchool.Services.Models.Images.DbImageModel", b =>
                {
                    b.HasOne("OutOfSchool.Services.Models.Images.DbImageContentTypeModel", "ContentType")
                        .WithMany("Images")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("OutOfSchool.Services.Models.Images.DbImageContentTypeModel", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
