{{- if .Values.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-connection-string
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: "Opaque"
data:
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.connectionString.secret.name) | default dict }}
{{- $password := (get $secret.data .Values.connectionString.secret.key) | default "" | b64dec }}
{{- include "webapp.mysqlconnection" (dict "username" .Values.connectionString.username "password" $password "release" .Release.Name) | indent 2 }}
{{- end }}