{{- if .Values.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.fullname" . }}-connection-string
  namespace:  {{ .Release.Namespace }}
  labels:
    {{ include "outofschool.labels" . }}
type: "Opaque"
data:
{{- include "webapp.mysqlconnection" (dict "username" .Values.connectionString.username "secretname" .Values.connectionString.secret.name "secretkey" .Values.connectionString.secret.key "namespace" .Release.Namespace) | indent 2 }}
{{- end }}