apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deploy.replicaCount }}
  selector:
    matchLabels:
      {{- include "webapp.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploy.updateStrategy }}
  strategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  minReadySeconds: {{ .Values.deploy.minReadySeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webapp.labels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "webapp.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.podSecurity.enabled }}
      securityContext:
        {{- toYaml .Values.podSecurity.context | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.fullTagOverride }}
          image: "{{ .Values.image.fullTagOverride }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.containerSecurity.enabled }}
          securityContext:
            {{- toYaml .Values.containerSecurity.context | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle:
            {{- toYaml .Values.lifecycleHooks | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.deploy.containerPort | quote }}
          {{- $env := merge (.Values.configuration.extraEnvironment | default dict) (.Values.global.extraEnvironment | default dict) -}}
          {{- range $k, $v := $env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
          {{- range $secret := .Values.configuration.secrets }}
          {{- if eq $secret.type "env" }}
          {{- range $key := $secret.keys }}
            {{- $envPrefix := $secret.prefix | default "" | upper }}
            {{- $envKey := (index $key "envKey") | default (index $key "key") | replace "." "_" | replace "-" "_" }}
            {{/* TODO: can't belive helm has not fixed booleans in 5 years ;) */}}
            {{- $uppedKey := ternary (upper $envKey) $envKey (list nil true "true" | has (index $key "upper")) }}
            - name: {{ $envPrefix }}{{ $uppedKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.name }}
                  key: {{ index $key "key" }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if or .Values.configuration.extraEnvVarsCM .Values.configuration.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.configuration.extraEnvVarsCM }}
            - configMapRef:
                name: {{ tpl .Values.configuration.extraEnvVarsCM . | quote }}
            {{- end }}
            {{- if .Values.configuration.extraEnvVarsSecret }}
            - secretRef:
                name: {{ tpl .Values.configuration.extraEnvVarsSecret . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.deploy.containerPort }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              port: http
              path: {{ .Values.livenessProbe.path }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- else if .Values.customLivenessProbe }}
          livenessProbe:
            {{- toYaml .Values.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              port: http
              path: {{ .Values.readinessProbe.path }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- else if .Values.customReadinessProbe }}
          readinessProbe:
            {{- toYaml .Values.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.storage.extraVolumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storage.extraVolumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
