apiVersion: v2
name: all-infrastructure
description: A support Helm library chart to track all dependencies

type: library

version: 1.0.0

appVersion: ""

dependencies:
  - name: cert-manager
    version: v1.11.0
    repository: https://charts.jetstack.io
  - name: mysql
    version: 9.7.1
    repository: https://charts.bitnami.com/bitnami
  - name: phpmyadmin
    version: 10.4.6
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.9.3
    repository: https://charts.bitnami.com/bitnami
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
  - name: vector
    version: 0.20.1
    repository: https://helm.vector.dev
  - name: ingress-nginx
    version: 4.3.0
    repository: https://kubernetes.github.io/ingress-nginx
  - name: outofschool
    version: 1.0.0
    repository: "file://../outofschool"