architecture: standalone
auth:
  enabled: true
  sentinel: true
  existingSecret: redis-auth
  existingSecretPasswordKey: password
  usePasswordFiles: false
master:
  persistence:
    enabled: true
    existingClaim: redis-master
# commonConfiguration: |-
#   # Enable AOF https://redis.io/topics/persistence#append-only-file
#   appendonly yes
#   # Disable RDB persistence, AOF persistence already enabled.
#   save ""