# Default values for outofschool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: {}

nameOverride: ""
fullnameOverride: ""

image:
  registry: gcr.io
  repository: gcp101292-pozashkillya
  name: oos-api
  pullPolicy: IfNotPresent
deploy:
  containerPort: 8080
