ingress-nginx:
  enabled: true
  controller:
    service:
      enabled: true
      externalTrafficPolicy: Local
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
    config:
      proxy-body-size: 100m
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  defaultBackend:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
