controller:
  service:
    enabled: true
    externalTrafficPolicy: Local
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  config:
    proxy-body-size: 100m
    use-forwarded-headers: "true"
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
defaultBackend:
  enabled: true
  autoscaling:
    # TODO: wait till the bug fix will be updated as a chart of HPA
    enabled: false
    minReplicas: 1
    maxReplicas: 2
