mongodb:
  enabled: true
  architecture: standalone
  useStatefulSet: true
  auth:
    enabled: true
    rootUser: root
    usernames: ["oos"]
    databases: ["outofschool"]
    existingSecret: "mongodb-credentials"
  persistence:
    enabled: true
    storageClass: "standard"
    size: 30Gi
  metrics:
    enabled: false

webapi:
  enabled: false
identity:
  enabled: false
frontend:
  enabled: false
mysql:
  enabled: false
phpmyadmin:
  enabled: false
cert-manager:
  enabled: false
elasticsearch:
  enabled: false
kibana:
  enabled: false
ingress-nginx:
  enabled: false