credentials:
  root:
    user: root
    password: ""
    host: "%"
serverVersion: 8.0.33
tls:
  useSelfSigned: true
serverInstances: 1
router:
  instances: 1
podSpec:
  containers:
  - name: mysql
    resources:
      requests:
        memory: "512Mi"
        # cpu: "1800m"
      limits:
        memory: "1Gi"
        # cpu: "3600m"
datadirVolumeClaimTemplate:
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
backupProfiles:
- name: dump-instance
  dumpInstance:
    dumpOptions:
      excludeTables:
      - outofschool.PersistedGrants
    storage:
      persistentVolumeClaim:
        claimName: mysql-backup-pvc
backupSchedules:
- name: backup-schedule
  schedule: "0 2 * * *"
  deleteBackupData: true
  backupProfileName: dump-instance
  enabled: true
serverConfig:
  mycnf: |
    [mysqld]
    default-time-zone = 'Europe/Kiev'
# TODO: Replace by a Job
# my_init_script.sh: |
#   #!/bin/bash
#   mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
#   CREATE USER 'api'@'%' IDENTIFIED BY '${API_PASSWORD}';
#   GRANT INSERT ON outofschool.* TO 'api'@'%';
#   GRANT SELECT ON outofschool.* TO 'api'@'%';
#   GRANT UPDATE ON outofschool.* TO 'api'@'%';
#   GRANT DELETE ON outofschool.* TO 'api'@'%';
#   FLUSH PRIVILEGES;
#   EOF
