mysql:
  enabled: true
  architecture: standalone
  rbac:
    create: true
  auth:
    database: outofschool
    username: "oos"
    replicationUser: replicator
    existingSecret: "mysql-auth"
    forcePassword: false
    usePasswordFiles: false
  initdbScripts:
    my_init_script.sh: |
      #!/bin/bash
      mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
      CREATE USER 'api'@'%' IDENTIFIED BY '${API_PASSWORD}';
      GRANT INSERT ON outofschool.* TO 'api'@'%';
      GRANT SELECT ON outofschool.* TO 'api'@'%';
      GRANT UPDATE ON outofschool.* TO 'api'@'%';
      GRANT DELETE ON outofschool.* TO 'api'@'%';
      FLUSH PRIVILEGES;
      EOF
  primary:
    persistence:
      enabled: true
      storageClass: standard
      size: 10Gi 
    extraEnvVarsSecret: mysql-api-auth

phpmyadmin:
  enabled: true
  ingress:
    enabled: true
    hostname: ""
    pathType: ImplementationSpecific
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: "letsencrypt"
      cert-manager.io/duration: 2160h0m0s
      cert-manager.io/renew-before: 168h0m0s
    tls: true
    ingressClassName: nginx
  db:
    allowArbitraryServer: false
    host: "mysql"

ingress-nginx:
  enabled: false
elasticsearch:
  enabled: false
kibana:
  enabled: false
webapi:
  enabled: false
identity:
  enabled: false
frontend:
  enabled: false
cert-manager:
  enabled: false
mongodb:
  enabled: false