enabled: true
ingress:
  enabled: true
  hostname: ""
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/issuer: "letsencrypt"
    cert-manager.io/duration: 2160h0m0s
    cert-manager.io/renew-before: 168h0m0s
  tls: true
  ingressClassName: nginx
db:
  allowArbitraryServer: false
  host: "mysql-instances"
